name: searxng

services:
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    env_file: ./.env
    volumes:
      - ./config/:/etc/searxng/:ro
      - core-data:/var/cache/searxng/
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  nextjs:
    container_name: searxng-nextjs
    build: .
    restart: always
    ports:
      - 3001:3000
    environment:
      SEARXNG_URL: http://searxng-core:8080
      GROQ_API_KEY: ${GROQ_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
      AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
      AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    volumes:
      - db-data:/app/data
    depends_on:
      core:
        condition: service_healthy

volumes:
  core-data:
  db-data:
